---
apiVersion: v1
kind: Namespace
metadata:
  name: spacex
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: spacex
  name: location-deploy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: location-app
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: location-app
    spec:
      containers:
      - image: erangi123/satellitelocation-user:main
        imagePullPolicy: Always
        name: location-app
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  namespace: spacex
  name: location-service
spec:
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: location-app
  type: LoadBalancer
status:
  loadBalancer: {}


          
